const spells = {
    //standard
    "Wind Strike": 2,
    "Water Strike": 4,
    "Earth Strike": 6,
    "Fire Strike": 8,
    "Wind Bolt": 9,
    "Water Bolt": 10,
    "Earth Bolt": 11,
    "Fire Bolt": 12,
    "Crumble Undead": 15,
    "Wind Blast": 13,
    "Water Blast": 14,
    "Iban Blast": 25,
    "Earth Blast": 15,
    "Fire Blast": 16,
    "Saradomin Strike": 20,
    "Claws of Guthix": 20,
    "Flames of Zamorak": 20,
    "Wind Wave": 17,
    "Water Wave": 18,
    "Earth Wave": 19,
    "Fire Wave": 20,
    "Wind Surge": 21,
    "Water Surge": 22,
    "Earth Surge": 23,
    "Fire Surge": 24,

    //ancients
    "Smoke Rush": 13,
    "Shadow Rush": 14,
    "Blood Rush": 15,
    "Ice Rush": 16,
    "Smoke Burst": 17,
    "Shadow Burst": 18,
    "Blood Burst": 21,
    "Ice Burst": 22,
    "Smoke Blitz": 23,
    "Shadow Blitz": 24,
    "Blood Blitz": 25,
    "Ice Blitz": 26,
    "Smoke Barrage": 27,
    "Shadow Barrage": 28,
    "Blood Barrage": 29,
    "Ice Barrage": 30,

    //arceuus
    "Ghostly Grasp": 12,
    "Skeletal Grasp": 17,
    "Undead Grasp": 24,
    "Inferior Demonbane": 16,
    "Superior Demonbane": 23,
    "Dark Demonbane": 30,
}