export const Ammunitions = [
   "Adamant arrow 5",
   "Adamant bolts 5",
   "Adamant brutal 5",
   "Adamant javelin",
   "Amethyst arrow 5",
   "Amethyst broad bolts 5",
   "Amethyst javelin",
   "Ancient blessing",
   "Barbed arrow 5",
   "Barbed bolts 5",
   "Black brutal 5",
   "Blunt arrow 5",
   "Blurite bolts 5",
   "Bolt rack 5",
   "Bone bolts 5",
   "Broad arrows 5",
   "Broad bolts 5",
   "Bronze arrow 5",
   "Bronze bolts 5",
   "Bronze brutal 5",
   "Bronze javelin",
   "Bullet arrow 5",
   "Diamond bolts 5",
   "Diamond bolts (e) 5",
   "Diamond dragon bolts 5",
   "Diamond dragon bolts (e) 5",
   "Dragon arrow 5",
   "Dragon bolts 5",
   "Dragon javelin",
   "Dragonstone bolts 5",
   "Dragonstone bolts (e) 5",
   "Dragonstone dragon bolts 5",
   "Dragonstone dragon bolts (e) 5",
   "Emerald bolts 5",
   "Emerald bolts (e) 5",
   "Emerald dragon bolts 5",
   "Emerald dragon bolts (e) 5",
   "Field arrow 5",
   "Ghommal's lucky penny",
   "Guam tar",
   "Hallowed grapple",
   "Harralander tar",
   "Holy blessing",
   "Honourable blessing",
   "Ice arrows 5",
   "Iron arrow 5",
   "Iron bolts 5",
   "Iron brutal 5",
   "Iron javelin",
   "Jade bolts 5",
   "Jade bolts (e) 5",
   "Jade dragon bolts 5",
   "Jade dragon bolts (e) 5",
   "Kebbit bolts",
   "Long kebbit bolts",
   "Marrentill tar",
   "Mith grapple",
   "Mithril arrow 5",
   "Mithril bolts 5",
   "Mithril brutal 5",
   "Mithril javelin 5",
   "Ogre arrow 5",
   "Onyx bolts 5",
   "Onyx bolts (e) 5",
   "Onyx dragon bolts",
   "Onyx dragon bolts (e)",
   "Opal bolts",
   "Opal bolts (e)",
   "Opal dragon bolts 5",
   "Opal dragon bolts (e) 5",
   "Peaceful blessing",
   "Pearl bolts 5",
   "Pearl bolts (e) 5",
   "Pearl dragon bolts 5",
   "Pearl dragon bolts (e) 5",
   "Rada's blessing 1",
   "Rada's blessing 2",
   "Rada's blessing 3",
   "Rada's blessing 4",
   "Ruby bolts 5",
   "Ruby bolts (e) 5",
   "Ruby dragon bolts 5",
   "Ruby dragon bolts (e) 5",
   "Rune arrow 5",
   "Rune brutal 5",
   "Rune javelin",
   "Runite bolts 5",
   "Sapphire bolts 5",
   "Sapphire bolts (e) 5",
   "Sapphire dragon bolts 5",
   "Sapphire dragon bolts (e) 5",
   "Silver bolts 5",
   "Steel arrow 5",
   "Steel bolts 5",
   "Steel brutal 5",
   "Steel javelin",
   "Tarromin tar",
   "Terrifying charm",
   "Topaz bolts 5",
   "Topaz bolts (e) 5",
   "Topaz dragon bolts 5",
   "Topaz dragon bolts (e) 5",
   "Training arrows 5",
   "Unholy blessing",
   "War blessing"
];