export const Bodys = [
   "3rd age druidic robe top",
   "3rd age platebody",
   "3rd age range top",
   "3rd age robe top",
   "Adamant chainbody",
   "Adamant platebody",
   "Ahrim's robetop",
   "Ancestral robe top",
   "Ancient ceremonial top",
   "Ancient d'hide body",
   "Ancient platebody",
   "Ancient robe top",
   "Angler top",
   "Ankou top",
   "Antisanta jacket",
   "Ardougne knight platebody",
   "Armadyl chestplate",
   "Armadyl d'hide body",
   "Armadyl platebody",
   "Armadyl robe top",
   "Bandos chestplate",
   "Bandos d'hide body",
   "Bandos platebody",
   "Bandos robe top",
   "Banshee top",
   "Beekeeper's top",
   "Black chainbody",
   "Black d'hide body",
   "Black desert shirt",
   "Black elegant shirt",
   "Black naval shirt",
   "Black platebody",
   "Black robe",
   "Black wizard robe (g)",
   "Black wizard robe (t)",
   "Bloodbark body",
   "Blue d'hide body",
   "Blue elegant blouse",
   "Blue elegant shirt",
   "Blue naval shirt",
   "Blue robe top",
   "Blue wizard robe",
   "Bob's black shirt",
   "Bob's blue shirt",
   "Bob's green shirt",
   "Bob's purple shirt",
   "Bob's red shirt",
   "Bomber jacket",
   "Bronze chainbody",
   "Bronze platebody",
   "Brown apron",
   "Brown naval shirt",
   "Builder's shirt",
   "Bunny top",
   "Camo top",
   "Carnillean armour",
   "Carpenter's shirt",
   "Chicken wings",
   "Christmas jumper",
   "Citizen top",
   "Clue hunter garb",
   "Corrupted body (attuned)",
   "Corrupted body (basic)",
   "Corrupted body (perfected)",
   "Corrupted morrigan's leather body (bh)",
   "Corrupted platebody",
   "Corrupted statius's platebody (bh)#",
   "Corrupted vesta's chainbody (bh)",
   "Corrupted zuriel's robe top (bh)",
   "Cow top",
   "Cream robe top",
   "Crier coat",
   "Crystal body (Amlodd)#Active",
   "Crystal body (Amlodd)#Inactive",
   "Crystal body (Cadarn)#Active",
   "Crystal body (Cadarn)#Inactive",
   "Crystal body (Crwys)#Active",
   "Crystal body (Crwys)#Inactive",
   "Crystal body (Hefin)#Active",
   "Crystal body (Hefin)#Inactive",
   "Crystal body (Iorwerth)#Active",
   "Crystal body (Iorwerth)#Inactive",
   "Crystal body (Ithell)#Active",
   "Crystal body (Ithell)#Inactive",
   "Crystal body (Trahaearn)#Active",
   "Crystal body (Trahaearn)#Inactive",
   "Crystal body (attuned)",
   "Crystal body (basic)",
   "Crystal body (perfected)",
   "Crystal body#Active",
   "Crystal body#Inactive",
   "Dagon'hai robe top",
   "Dark infinity top",
   "Dark tuxedo jacket",
   "Desert camo top",
   "Desert shirt",
   "Desert top",
   "Desert top (overcoat)",
   "Dharok's platebody",
   "Dragon chainbody",
   "Dragon chainbody (cr)",
   "Dragon chainbody (g)",
   "Dragon platebody",
   "Dragon platebody (g)",
   "Dragonstone platebody",
   "Druid's robe top",
   "Eggshell platebody",
   "Elder chaos top",
   "Elder chaos top (or)",
   "Elite void top (or)",
   "Elite void top",
   "Elven top (white vest)",
   "Elven top (white)",
   "Elven top (yellow vest)",
   "Elven top (yellow)",
   "Enchanted top",
   "Evil chicken wings",
   "Farmer's jacket",
   "Farmer's shirt",
   "Fighter torso (or)",
   "Fighter torso",
   "Forestry top",
   "Fremennik beige shirt",
   "Fremennik blue shirt",
   "Fremennik brown shirt",
   "Fremennik grey shirt",
   "Fremennik red shirt",
   "Fremennik robe",
   "Frog-leather body",
   "Ghostly robe (top)",
   "Gilded chainbody",
   "Gilded d'hide body",
   "Gilded platebody",
   "Golden apron",
   "Golden prospector jacket",
   "Graahk top",
   "Graceful top#Worn",
   "Granite body",
   "Green d'hide body",
   "Green d'hide body (g)",
   "Green d'hide body (t)",
   "Green elegant blouse",
   "Green elegant shirt",
   "Green goblin mail",
   "Green naval shirt",
   "Green robe top",
   "Grey naval shirt",
   "Grey robe top",
   "Guthan's platebody",
   "Guthix d'hide body",
   "Guthix platebody",
   "Guthix robe top",
   "Ham shirt",
   "Hardcore ironman platebody",
   "Hardleather body",
   "Infinity top",
   "Initiate hauberk",
   "Inquisitor's hauberk",
   "Iron chainbody",
   "Iron platebody",
   "Ironman platebody",
   "Jungle camo top",
   "Justiciar chestguard",
   "Karil's leathertop",
   "Khazard armour",
   "Kyatt top",
   "Larupia top",
   "Leather body",
   "Leather body (g)",
   "Lederhosen top",
   "Light infinity top",
   "Light tuxedo jacket",
   "Lumberjack top",
   "Lunar torso",
   "Masori body",
   "Masori body (f)",
   "Medical gown",
   "Menaphite purple top",
   "Menaphite red top",
   "Mime top",
   "Mithril chainbody",
   "Mithril platebody",
   "Monk's robe top",
   "Monk's robe top (g)",
   "Monk's robe top (t)",
   "Moonclan armour",
   "Morrigan's leather body (bh)",
   "Mourner top",
   "Mummy's body",
   "Musketeer tabard",
   "Mystic robe top",
   "Nutcracker top#Festive",
   "Nutcracker top#Sweet",
   "Obsidian platebody",
   "Oldschool jumper",
   "Orange goblin mail",
   "Ornate top",
   "Pink elegant blouse",
   "Pink elegant shirt",
   "Pink goblin mail",
   "Pink robe top",
   "Plague jacket",
   "Poet's jacket",
   "Polar camo top",
   "Priest gown (top)",
   "Prince tunic",
   "Princess blouse",
   "Proselyte hauberk",
   "Prospector jacket",
   "Purple elegant blouse",
   "Purple elegant shirt",
   "Purple goblin mail",
   "Purple naval shirt",
   "Purple robe top",
   "Pyromancer garb",
   "Rangers' tunic",
   "Red d'hide body",
   "Red d'hide body (g)",
   "Red d'hide body (t)",
   "Red elegant blouse",
   "Red elegant shirt",
   "Red goblin mail",
   "Red naval shirt",
   "Red robe top",
   "Robe of elidinis (top)",
   "Robe top of darkness",
   "Robe top of ruin",
   "Robe top of the eye#Blue",
   "Robe top of the eye#Green",
   "Robe top of the eye#Red",
   "Robe top of the eye#Regular",
   "Rock-shell plate",
   "Rogue top",
   "Rune chainbody",
   "Rune platebody",
   "Samurai shirt",
   "Sandwich lady top",
   "Sanguine torva platebody",
   "Santa jacket",
   "Saradomin d'hide body",
   "Saradomin platebody",
   "Saradomin robe top",
   "Shade robe top",
   "Shayzien body (5)",
   "Shirt (brown)",
   "Shirt (lilac)",
   "Shirt (yellow)",
   "Silly jester top",
   "Skeletal top",
   "Skeleton shirt",
   "Slave shirt",
   "Smiths tunic",
   "Snakeskin body",
   "Spined body",
   "Spirit angler top",
   "Splitbark body",
   "Spookier robe",
   "Spooky robe#Reward",
   "Statius's platebody (bh)",
   "Steel chainbody",
   "Steel platebody",
   "Steel platebody (g)",
   "Steel platebody (t)",
   "Stripy pirate shirt (beige)",
   "Stripy pirate shirt (blue)",
   "Stripy pirate shirt (brown)",
   "Stripy pirate shirt (red)",
   "Studded body",
   "Studded body (g)",
   "Studded body (t)",
   "Swampbark body",
   "Teal robe top",
   "Torag's platebody",
   "Torva platebody",
   "Tree top",
   "Turquoise robe top",
   "Twisted ancestral robe top",
   "Ultimate ironman platebody",
   "Varrock armour 1",
   "Varrock armour 2",
   "Varrock armour 3",
   "Varrock armour 4",
   "Verac's brassard",
   "Vesta's chainbody (bh)",
   "Virtus robe top",
   "Void knight top (or)",
   "Void knight top",
   "Vyre noble blazer (grey)",
   "Vyre noble blazer (purple)",
   "Vyre noble blazer (red)",
   "Vyre noble corset (grey)",
   "Vyre noble corset (purple)",
   "Vyre noble corset (red)",
   "Vyre noble dress top (grey)",
   "Vyre noble dress top (purple)",
   "Vyre noble dress top (red)",
   "Vyre noble top",
   "Vyre noble vest (grey)",
   "Vyre noble vest (purple)",
   "Vyre noble vest (red)",
   "Vyrewatch top",
   "White apron",
   "White chainbody",
   "White elegant blouse",
   "White goblin mail",
   "White platebody",
   "Witch top",
   "Wood camo top",
   "Xerician top",
   "Yak-hide armour (top)",
   "Yellow goblin mail",
   "Yellow robe top",
   "Zamorak d'hide body",
   "Zamorak monk top",
   "Zamorak platebody",
   "Zamorak robe top",
   "Zealot's robe top",
   "Zombie shirt",
   "Zuriel's robe top (bh)"
];