export const Capes = [
   "3rd age cloak",
   "3rd age druidic cloak",
   "Achievement diary cape",
   "Adventurer's cape",
   "Agility cape",
   "Ancient cloak",
   "Ardougne cloak 1",
   "Ardougne cloak 2",
   "Ardougne cloak 3",
   "Ardougne cloak 4",
   "Armadyl cloak",
   "Attack cape",
   "Ava's accumulator",
   "Ava's assembler",
   "Ava's attractor",
   "Banana cape",
   "Bandos cloak",
   "Black cape",
   "Blue cape",
   "Bonesack",
   "Cabbage cape",
   "Cape of legends",
   "Cape of skulls",
   "Champion's cape",
   "Cloak of ruin",
   "Clue hunter cloak",
   "Cobweb cape",
   "Construct. cape",
   "Cooking cape",
   "Crafting cape",
   "Defence cape",
   "Diving apparatus",
   "Eagle cape",
   "Explorer backpack",
   "Farming cape",
   "Fire cape",
   "Firemaking cape",
   "Fish sack",
   "Fish sack barrel#Closed",
   "Fish sack barrel#Open",
   "Fishing cape",
   "Fletching cape",
   "Forestry basket#Closed",
   "Forestry basket#Open",
   "Forestry kit",
   "Gauntlet cape",
   "Ghostly cloak",
   "Gnome child backpack",
   "Green cape",
   "Guthix cape",
   "Guthix cloak",
   "Ham cloak",
   "Herblore cape",
   "Hitpoints cape",
   "Hunter cape",
   "Imbued guthix cape",
   "Imbued saradomin cape",
   "Imbued zamorak cape",
   "Infernal cape",
   "Infinite money bag",
   "Jester cape",
   "Kruk jr",
   "Log basket",
   "Lost bag",
   "Lunar cape",
   "Magic cape",
   "Max cape",
   "Mining cape",
   "Moonclan cape",
   "Mourner cloak",
   "Music cape",
   "Mythical cape",
   "Obsidian cape",
   "Orange cape",
   "Ornate cape",
   "Pheasant cape",
   "Pink cape",
   "Prayer cape",
   "Purple cape",
   "Quest point cape",
   "Ranging cape",
   "Red cape",
   "Red cape (Soul Wars)",
   "Runecraft cape",
   "Sack of presents",
   "Santa's list",
   "Saradomin cape",
   "Saradomin cloak",
   "Scroll sack",
   "Shoulder parrot",
   "Slayer cape",
   "Smithing cape",
   "Spotted cape#Worn",
   "Spottier cape#Worn",
   "Strength cape",
   "Thieving bag",
   "Thieving cape",
   "Witch cape",
   "Wolf cloak",
   "Woodcutting cape",
   "Yellow cape",
   "Zamorak cape",
   "Zamorak cloak",
];