export const Capes = [
   "3rd age cloak",
   "3rd age druidic cloak",
   "Accumulator max cape",
   "Achievement diary cape",
   "Adventurer's cape",
   "Agility cape",
   "Ancient cloak",
   "Ardougne cloak 1",
   "Ardougne cloak 2",
   "Ardougne cloak 3",
   "Ardougne cloak 4",
   "Ardougne max cape",
   "Armadyl cloak",
   "Assembler max cape",
   "Attack cape",
   "Ava's accumulator",
   "Ava's assembler",
   "Ava's attractor",
   "Banana cape",
   "Bandos cloak",
   "Black cape",
   "Black coffin#Closed",
   "Black coffin#Open",
   "Blue cape",
   "Bonesack",
   "Bronze coffin#Closed",
   "Bronze coffin#Open",
   "Cabbage cape",
   "Cape of legends",
   "Cape of skulls",
   "Champion's cape",
   "Cloak of ruin",
   "Clockwork suit#Unwound",
   "Clue hunter cloak",
   "Cobweb cape",
   "Construct. cape",
   "Cooking cape",
   "Crafting cape",
   "Deadman's cape#Cosmetic",
   "Deadman's cape#Deadman Mode",
   "Decorative armour (quiver)",
   "Defence cape",
   "Diving apparatus",
   "Eagle cape",
   "Explorer backpack",
   "Farming cape",
   "Fire cape#Broken",
   "Fire cape#Locked",
   "Fire cape#Normal",
   "Fire max cape#Broken",
   "Fire max cape#Locked",
   "Fire max cape#Normal",
   "Firemaking cape",
   "Fish sack",
   "Fish sack barrel#Closed",
   "Fish sack barrel#Open",
   "Fishing cape",
   "Fletching cape",
   "Forestry basket#Closed",
   "Forestry basket#Open",
   "Forestry kit",
   "Fremennik black cloak",
   "Fremennik blue cloak",
   "Fremennik brown cloak",
   "Fremennik cyan cloak",
   "Fremennik green cloak",
   "Fremennik grey cloak",
   "Fremennik pink cloak",
   "Fremennik purple cloak",
   "Fremennik red cloak",
   "Fremennik teal cloak",
   "Fremennik yellow cloak",
   "Gauntlet cape",
   "Ghostly cloak",
   "Gnome child backpack",
   "Gold coffin#Closed",
   "Gold coffin#Open",
   "Green cape",
   "Guthix cape",
   "Guthix cloak",
   "Guthix max cape",
   "Ham cloak",
   "Herblore cape",
   "Hitpoints cape",
   "Hooded cloak#Saradomin",
   "Hooded cloak#Zamorak",
   "Hunter cape",
   "Imbued guthix cape",
   "Imbued guthix max cape",
   "Imbued saradomin cape",
   "Imbued saradomin max cape",
   "Imbued zamorak cape",
   "Imbued zamorak max cape",
   "Infernal cape",
   "Infernal max cape",
   "Infinite money bag",
   "Jester cape",
   "Kruk jr",
   "Log basket",
   "Lost bag",
   "Lunar cape",
   "Magic cape",
   "Maniacal monkey (item)",
   "Masori assembler max cape",
   "Masori assembler",
   "Max cape#Worn",
   "Mining cape",
   "Moonclan cape",
   "Mourner cloak",
   "Music cape",
   "Mythical cape",
   "Mythical max cape",
   "Obsidian cape",
   "Obsidian cape (r)",
   "Orange cape",
   "Ornate cape",
   "Pheasant cape",
   "Pink cape",
   "Prayer cape",
   "Princely monkey",
   "Purple cape",
   "Quest point cape",
   "Ranging cape",
   "Red cape",
   "Red cape (Soul Wars)",
   "Runecraft cape",
   "Sack of presents",
   "Santa's list",
   "Saradomin cape",
   "Saradomin cloak",
   "Saradomin max cape",
   "Scroll sack",
   "Shoulder parrot",
   "Silver coffin",
   "Slayer cape",
   "Smithing cape",
   "Snow imp costume tail#Reward",
   "Soul cape#Blue",
   "Soul cape#Red",
   "Spotted cape#Worn",
   "Spottier cape#Worn",
   "Steel coffin#Closed",
   "Steel coffin#Open",
   "Strength cape",
   "Thieving bag",
   "Thieving cape",
   "Victor's cape (1)",
   "Victor's cape (10)",
   "Victor's cape (100)",
   "Victor's cape (1000)",
   "Victor's cape (50)",
   "Victor's cape (500)",
   "Web cloak",
   "Witch cape",
   "Wolf cloak",
   "Woodcutting cape",
   "Xeric's champion",
   "Xeric's general",
   "Xeric's guard",
   "Xeric's sentinel",
   "Xeric's warrior",
   "Yellow cape",
   "Zamorak cape",
   "Zamorak cloak",
   "Zamorak max cape",
   "Zombie monkey (item)"
];