export const Feets = [
   "Adamant boots",
   "Ancient ceremonial boots",
   "Ancient d'hide boots",
   "Angler boots",
   "Ankou socks",
   "Antisanta boots",
   "Armadyl d'hide boots",
   "Bandos boots",
   "Bandos d'hide boots",
   "Bear feet",
   "Beekeeper's boots",
   "Black boots",
   "Bloodbark boots",
   "Blue boots",
   "Bob the cat slippers",
   "Boots of brimstone",
   "Boots of darkness",
   "Boots of lightness",
   "Boots of stone",
   "Boots of the eye",
   "Bronze boots",
   "Builder's boots",
   "Bunny feet",
   "Carpenter's boots",
   "Chicken feet",
   "Citizen shoes",
   "Climbing boots",
   "Climbing boots (g)",
   "Clue hunter boots",
   "Cow shoes",
   "Cream boots",
   "Dark flippers",
   "Dark tuxedo shoes",
   "Decorative boots (gold)",
   "Decorative boots (red)",
   "Decorative boots (white)",
   "Demon feet",
   "Desert boots",
   "Devout boots",
   "Dragon boots",
   "Dragon boots (cr)",
   "Dragon boots (g)",
   "Dragonstone boots",
   "Elven boots",
   "Eternal boots",
   "Evil chicken feet",
   "Fancier boots",
   "Fancy boots",
   "Farmer's boots",
   "Festive elf slippers",
   "Fighting boots",
   "Flippers",
   "Forestry boots",
   "Fremennik boots",
   "Fremennik sea boots 1",
   "Fremennik sea boots 2",
   "Fremennik sea boots 3",
   "Fremennik sea boots 4",
   "Frog slippers",
   "Frog-leather boots",
   "Gardening boots",
   "Ghostly boots",
   "Gilded boots",
   "Golden prospector boots",
   "Granite boots",
   "Green boots",
   "Grey boots",
   "Guardian boots",
   "Guthix d'hide boots",
   "Ham boots",
   "Holy sandals",
   "Infinity boots",
   "Insulated boots",
   "Iron boots",
   "Jad slippers",
   "Leather boots",
   "Light tuxedo shoes",
   "Lumberjack boots",
   "Lunar boots",
   "Mime boots",
   "Mithril boots",
   "Mole slippers",
   "Moonclan boots",
   "Mourner boots",
   "Mummy's feet",
   "Mystic boots",
   "Ornate boots",
   "Pegasian boots",
   "Pheasant boots",
   "Pink boots",
   "Pirate boots",
   "Primordial boots",
   "Prospector boots",
   "Purple boots",
   "Pyromancer boots",
   "Ranger boots",
   "Red boots",
   "Rock-shell boots",
   "Rogue boots",
   "Rune boots",
   "Runner boots",
   "Sage's greaves",
   "Samurai boots",
   "Santa boots",
   "Saradomin d'hide boots",
   "Shayzien boots (5)",
   "Shoes",
   "Silly jester boots",
   "Skeletal boots",
   "Skeleton boots",
   "Slave boots",
   "Smiths boots",
   "Snakeskin boots",
   "Socks of ruin",
   "Spiked boots",
   "Spiked manacles",
   "Spined boots",
   "Spirit angler boots",
   "Splitbark boots",
   "Spookier boots",
   "Steel boots",
   "Swampbark boots",
   "Teal boots",
   "Turquoise boots",
   "Vyre noble shoes",
   "Vyrewatch shoes",
   "White boots",
   "Witch boots",
   "Wizard boots",
   "Yellow boots",
   "Zamorak d'hide boots",
   "Zealot's boots",
   "Zombie boots"
];