export const Hands = [
   "20th anniversary gloves",
   "3rd age vambraces",
   "Adamant gloves",
   "Adventurer's vambraces",
   "Ancient bracers",
   "Ancient ceremonial gloves",
   "Ankou gloves",
   "Antisanta gloves",
   "Armadyl bracers",
   "Bandos bracers",
   "Barrows gloves",
   "Beekeeper's gloves",
   "Black d'hide vambraces",
   "Black gloves",
   "Black spiky vambraces",
   "Bloodbark gauntlets",
   "Blue d'hide vambraces",
   "Blue spiky vambraces",
   "Bracelet of clay",
   "Bracelet of ethereum",
   "Bracelet of slaughter",
   "Bronze gloves",
   "Bunny paws",
   "Chaos gauntlets",
   "Clue hunter gloves",
   "Combat bracelet",
   "Cooking gauntlets",
   "Cow gloves",
   "Crab claw",
   "Crabclaw hook",
   "Dark tuxedo cuffs",
   "Diamond bracelet",
   "Dragon gloves",
   "Dragonstone bracelet",
   "Dragonstone gauntlets",
   "Elven gloves",
   "Emerald bracelet",
   "Expeditious bracelet",
   "Expert mining gloves",
   "Ferocious gloves",
   "Flamtaer bracelet",
   "Fremennik gloves",
   "Ghostly gloves",
   "Gilded d'hide vambraces",
   "Gloves of darkness",
   "Gloves of ruin",
   "Gloves of silence",
   "Gold bracelet",
   "Granite gloves",
   "Green d'hide vambraces",
   "Green spiky vambraces",
   "Grey gloves",
   "Guthix bracers",
   "Ham gloves",
   "Hardleather gloves",
   "Holy wraps",
   "Ice gloves",
   "Infinity gloves",
   "Inoculation bracelet",
   "Iron gloves",
   "Jade bracelet",
   "Karamja gloves 1",
   "Karamja gloves 2",
   "Karamja gloves 3",
   "Karamja gloves 4",
   "Klank's gauntlets",
   "Leather gloves",
   "Leather vambraces",
   "Light tuxedo cuffs",
   "Lunar gloves",
   "Mime gloves",
   "Mining gloves",
   "Mithril gloves",
   "Moonclan gloves",
   "Mourner gloves",
   "Mummy's hands",
   "Mystic gloves",
   "Onyx bracelet",
   "Opal bracelet",
   "Ornate gloves",
   "Penance gloves",
   "Pirate's hook",
   "Purple gloves",
   "Ranger gloves",
   "Red d'hide vambraces",
   "Red gloves",
   "Red spiky vambraces",
   "Regen bracelet",
   "Rock-shell gloves",
   "Rogue gloves",
   "Ruby bracelet",
   "Rune gloves",
   "Samurai gloves",
   "Santa gloves",
   "Sapphire bracelet",
   "Saradomin bracers",
   "Shayzien gloves (5)",
   "Skeletal gloves",
   "Skeleton gloves",
   "Slayer gloves",
   "Smiths gloves",
   "Smiths gloves (i)",
   "Snakeskin vambraces",
   "Spiky vambraces",
   "Spined gloves",
   "Splitbark gauntlets",
   "Spookier gloves",
   "Steel gauntlets",
   "Steel gloves",
   "Superior mining gloves",
   "Swampbark gauntlets",
   "Teal gloves",
   "Topaz bracelet",
   "Tormented bracelet",
   "Twitcher's gloves",
   "Villager armband (blue)",
   "Villager armband (brown)",
   "Villager armband (pink)",
   "Villager armband (yellow)",
   "Void knight gloves",
   "Warm gloves",
   "White gloves",
   "Yellow gloves",
   "Zamorak bracers",
   "Zaryte vambraces",
   "Zenyte bracelet",
   "Zombie gloves"
];