export const Heads = [
   "3rd age full helmet",
   "3rd age mage hat",
   "3rd age range coif",
   "4th birthday hat",
   "A powdered wig",
   "Accumulator max hood",
   "Achievement diary hood",
   "Adamant dragon mask",
   "Adamant full helm",
   "Adamant med helm",
   "Agility hood",
   "Ahrim's hood",
   "Air tiara",
   "Ancestral hat",
   "Ancient ceremonial mask",
   "Ancient coif",
   "Ancient full helm",
   "Ancient halo#Broken",
   "Ancient halo#Locked",
   "Ancient halo#Normal",
   "Ancient mitre",
   "Angler hat",
   "Ankou mask",
   "Antisanta mask",
   "Arceuus hood",
   "Archer helm",
   "Ardougne knight helm",
   "Ardougne max hood",
   "Armadyl coif",
   "Armadyl full helm",
   "Armadyl halo",
   "Armadyl helmet",
   "Armadyl mitre",
   "Assembler max hood",
   "Attack hood",
   "Banana hat",
   "Bandos coif",
   "Bandos full helm",
   "Bandos halo",
   "Bandos mitre",
   "Banshee mask",
   "Beanie",
   "Bearhead",
   "Beekeeper's hat",
   "Beret mask",
   "Berserker helm",
   "Big pirate hat",
   "Black beret",
   "Black boater",
   "Black cavalier",
   "Black demon mask",
   "Black dragon mask",
   "Black full helm",
   "Black h'ween mask",
   "Black headband",
   "Black leprechaun hat",
   "Black mask (i)",
   "Black mask",
   "Black med helm",
   "Black partyhat",
   "Black santa hat",
   "Black slayer helmet",
   "Black tricorn hat",
   "Black unicorn mask",
   "Black wizard hat (g)",
   "Black wizard hat (t)",
   "Blacksmith's helm",
   "Blood tiara",
   "Blood'n'tar snelm (pointed)",
   "Blood'n'tar snelm (round)",
   "Bloodbark helm",
   "Blue beret",
   "Blue boater",
   "Blue dragon mask",
   "Blue halloween mask",
   "Blue hat",
   "Blue headband",
   "Blue partyhat",
   "Blue tricorn hat",
   "Blue wizard hat",
   "Bobble hat",
   "Body tiara",
   "Bomber cap",
   "Bowl wig",
   "Brassica halo",
   "Broken bark snelm",
   "Bronze dragon mask",
   "Bronze full helm",
   "Bronze full helm (g)",
   "Bronze full helm (t)",
   "Bronze med helm",
   "Brown headband",
   "Brown tricorn hat",
   "Bruise blue snelm (pointed)",
   "Bruise blue snelm (round)",
   "Bucket helm",
   "Bucket helm (g)",
   "Bunny ears",
   "Bunnyman mask",
   "Cake hat",
   "Camel mask",
   "Camo helmet",
   "Cap and goggles",
   "Carpenter's helmet",
   "Castlewars hood (Saradomin)",
   "Castlewars hood (Zamorak)",
   "Cat mask",
   "Catalytic tiara",
   "Cavalier mask",
   "Chaos tiara",
   "Chef's hat",
   "Chicken head",
   "Circlet of water",
   "Clown mask",
   "Coif",
   "Construct. hood",
   "Cooking hood",
   "Corrupted helm",
   "Corrupted helm (attuned)",
   "Corrupted helm (basic)",
   "Corrupted helm (perfected)",
   "Corrupted morrigan's coif (bh)",
   "Corrupted statius's full helm (bh)",
   "Corrupted zuriel's hood (bh)",
   "Cosmic tiara",
   "Cow mask",
   "Crab helmet",
   "Crafting hood",
   "Cream hat",
   "Crier hat",
   "Crystal crown (Amlodd)",
   "Crystal crown (Cadarn)",
   "Crystal crown (Crwys)",
   "Crystal crown (Hefin)",
   "Crystal crown (Iorwerth)",
   "Crystal crown (Ithell)",
   "Crystal crown (Meilyr)",
   "Crystal crown (Trahaearn)",
   "Crystal helm (Amlodd)#Active",
   "Crystal helm (Amlodd)#Inactive",
   "Crystal helm (Cadarn)#Active",
   "Crystal helm (Cadarn)#Inactive",
   "Crystal helm (Crwys)#Active",
   "Crystal helm (Crwys)#Inactive",
   "Crystal helm (Hefin)#Active",
   "Crystal helm (Hefin)#Inactive",
   "Crystal helm (Iorwerth)#Active",
   "Crystal helm (Iorwerth)#Inactive",
   "Crystal helm (Ithell)#Active",
   "Crystal helm (Ithell)#Inactive",
   "Crystal helm (Trahaearn)#Active",
   "Crystal helm (Trahaearn)#Inactive",
   "Crystal helm (attuned)",
   "Crystal helm (basic)",
   "Crystal helm (perfected)",
   "Crystal helm#Active",
   "Crystal helm#Inactive",
   "Cyclops head",
   "Dagon'hai hat",
   "Dark cavalier",
   "Dark infinity hat",
   "Death tiara",
   "Deerstalker",
   "Defence hood",
   "Desert disguise",
   "Dharok's helm",
   "Doctor's hat",
   "Double eye patch",
   "Dragon full helm",
   "Dragon full helm (g)",
   "Dragon med helm",
   "Dragon med helm (cr)",
   "Dragonstone full helm",
   "Druidic wreath",
   "Dwarven helmet",
   "Earmuffs",
   "Earth tiara",
   "Easter egg helm",
   "Easter hat",
   "Elder chaos hood",
   "Elder chaos hood (or)",
   "Elemental helmet",
   "Elemental tiara",
   "Enchanted hat",
   "Evil chicken head",
   "Facemask",
   "Fake beak",
   "Fancy tiara",
   "Farming hood",
   "Farseer helm",
   "Fedora",
   "Festive elf hat",
   "Festive games crown",
   "Fez",
   "Fighter hat",
   "Fire max hood",
   "Fire tiara",
   "Firemaking hood",
   "Fishbowl helmet",
   "Fishing hood",
   "Five barrels",
   "Fletching hood",
   "Forestry hat",
   "Four barrels",
   "Fremennik hat",
   "Fremennik helm",
   "Frog mask",
   "Gas mask",
   "Ghostly hood",
   "Giant boot",
   "Gilded coif",
   "Gilded full helm",
   "Gilded med helm",
   "Gnome child hat",
   "Gnome child mask",
   "Gnome goggles",
   "Goblin mask",
   "Gold headband",
   "Gold helmet",
   "Gold tiara",
   "Golden chef's hat",
   "Golden prospector helmet",
   "Graahk headdress",
   "Graceful hood",
   "Granite helm",
   "Gravedigger mask",
   "Greater demon mask",
   "Green boater",
   "Green dragon mask",
   "Green halloween mask",
   "Green hat",
   "Green headband",
   "Green partyhat",
   "Green slayer helmet",
   "Green tricorn hat",
   "Grey hat",
   "Grey tricorn hat",
   "Grim reaper hood",
   "Group iron helm",
   "Guthan's helm",
   "Guthix coif",
   "Guthix full helm",
   "Guthix halo",
   "Guthix max hood",
   "Guthix mitre",
   "Half moon spectacles",
   "Ham hood",
   "Hard hat",
   "Hardcore group iron helm",
   "Hardcore ironman helm",
   "Hat eyepatch",
   "Headless head",
   "Healer hat#Broken",
   "Healer hat#Locked",
   "Healer hat#Normal",
   "Hell cat ears",
   "Helm of neitiznot",
   "Helm of neitiznot (or)",
   "Helm of raedwald",
   "Herblore hood",
   "Highwayman mask",
   "Hitpoints hood",
   "Hood of darkness",
   "Hood of ruin",
   "Hornwood helm",
   "Hosidius hood",
   "Hunter hood",
   "Hunter's honour",
   "Hydra slayer helmet",
   "Icthlarin's hood (tier 5)",
   "Imbued guthix max hood",
   "Imbued saradomin max hood",
   "Imbued zamorak max hood",
   "Imp mask",
   "Infernal max hood",
   "Infinity hat",
   "Initiate sallet",
   "Inquisitor's great helm",
   "Inverted santa hat",
   "Iron dragon mask",
   "Iron full helm",
   "Iron med helm",
   "Ironman helm",
   "Jack lantern mask",
   "Jester hat",
   "Jungle demon mask",
   "Justiciar faceguard",
   "Kandarin headgear 1",
   "Kandarin headgear 2",
   "Kandarin headgear 3",
   "Kandarin headgear 4",
   "Karil's coif",
   "Khazard helmet",
   "Kyatt hat",
   "Larupia hat",
   "Lava dragon mask",
   "Law tiara",
   "Leather cowl",
   "Lederhosen hat",
   "Left eye patch",
   "Leprechaun hat",
   "Lesser demon mask",
   "Light infinity hat",
   "Lovakengj hood",
   "Lumberjack hat",
   "Lunar helm",
   "Magic hood",
   "Magma helm",
   "Mask of balance",
   "Mask of ranul",
   "Mask of rebirth",
   "Masori mask",
   "Masori mask (f)",
   "Max hood",
   "Menaphite purple hat",
   "Menaphite red hat",
   "Mime mask",
   "Mind helmet",
   "Mind tiara",
   "Mining hood",
   "Mithril dragon mask",
   "Mithril full helm",
   "Mithril med helm",
   "Monocle",
   "Moonclan hat",
   "Moonclan helm",
   "Morrigan's coif (bh)#",
   "Mudskipper hat",
   "Mummy's head",
   "Music hood",
   "Musketeer hat",
   "Myre snelm (pointed)",
   "Myre snelm (round)",
   "Mystic hat",
   "Mythical max hood",
   "Nature tiara",
   "Navy cavalier",
   "Neitiznot faceguard",
   "Nose peg",
   "Nurse hat",
   "Obsidian helmet",
   "Odd spectacles",
   "Old demon mask",
   "One barrel",
   "Orange boater",
   "Ornate helm",
   "Penguin mask",
   "Pheasant hat",
   "Pink boater",
   "Pink hat",
   "Pink headband",
   "Pirate hat",
   "Pirate's hat",
   "Piscarilius hood",
   "Pith helmet",
   "Prayer hood",
   "Propeller hat",
   "Proselyte sallet",
   "Prospector helmet",
   "Purple boater",
   "Purple hat",
   "Purple partyhat",
   "Purple slayer helmet",
   "Purple tricorn hat",
   "Pyromancer hood",
   "Quest point hood",
   "Rainbow partyhat",
   "Ram skull helm",
   "Ranger hat",
   "Ranging hood",
   "Red beret",
   "Red boater",
   "Red cavalier",
   "Red dragon mask",
   "Red halloween mask",
   "Red hat",
   "Red headband",
   "Red partyhat",
   "Red slayer helmet",
   "Red slayer helmet (i)",
   "Red tricorn hat",
   "Reindeer hat",
   "Reinforced goggles",
   "Right eye patch",
   "Robin hood hat",
   "Rock-shell helm",
   "Rogue mask",
   "Rogue's revenge",
   "Royal crown",
   "Rune dragon mask",
   "Rune full helm",
   "Rune med helm",
   "Runecraft hood",
   "Runner hat",
   "Sagacious spectacles",
   "Samurai kasa",
   "Sandwich lady hat",
   "Sanguine torva full helm",
   "Santa hat",
   "Santa mask",
   "Saradomin coif",
   "Saradomin full helm",
   "Saradomin halo",
   "Saradomin max hood",
   "Saradomin mitre",
   "Saucepan",
   "Seren halo",
   "Serpentine helm",
   "Shaman mask",
   "Shayzien helm (5)",
   "Silly jester hat",
   "Silver partyhat",
   "Skeletal helm",
   "Skeleton mask",
   "Slayer helmet",
   "Slayer helmet (i)",
   "Slayer hood",
   "Sleeping cap",
   "Smithing hood",
   "Snakeskin bandana",
   "Snow goggles %26 hat",
   "Spined helm",
   "Spiny helmet",
   "Spirit angler headband",
   "Splitbark helm",
   "Spookier hood",
   "Star-face",
   "Statius's full helm (bh)",
   "Steel dragon mask",
   "Steel full helm",
   "Steel med helm",
   "Strength hood",
   "Swampbark helm",
   "Tan cavalier",
   "Tanzanite helm",
   "Teal hat",
   "Thieving hood",
   "Three barrels",
   "Tiara",
   "Top hat",
   "Torag's helm",
   "Torva full helm",
   "Tri-jester hat",
   "Tribal mask (combat)",
   "Tribal mask (disease)",
   "Tribal mask (poison)",
   "Turquoise hat",
   "Turquoise slayer helmet",
   "Twisted ancestral hat",
   "Twisted slayer helmet",
   "Two barrels",
   "Tyras helm",
   "Tzkal slayer helmet",
   "Tztok slayer helmet",
   "Ultimate ironman helm",
   "Uri's hat",
   "Vampyric slayer helmet",
   "Vampyric slayer helmet (i)",
   "Verac's helm",
   "Virtus mask",
   "Void mage helm (or)",
   "Void mage helm",
   "Void melee helm (or)",
   "Void melee helm",
   "Void ranger helm (or)",
   "Void ranger helm",
   "Warrior helm",
   "Water tiara",
   "White beret",
   "White boater",
   "White cavalier",
   "White full helm",
   "White headband",
   "White med helm",
   "White partyhat",
   "White unicorn mask",
   "Wise old man's santa hat",
   "Witch hat",
   "Wizard hat",
   "Wolf mask",
   "Woodcutting hood",
   "Woolly hat",
   "Wrath tiara",
   "Xerician hat",
   "Yellow hat",
   "Yellow partyhat",
   "Zamorak coif",
   "Zamorak full helm",
   "Zamorak halo#Broken",
   "Zamorak halo#Locked",
   "Zamorak halo#Normal",
   "Zamorak max hood",
   "Zamorak mitre",
   "Zealot's helm",
   "Zombie mask",
   "Zuriel's hood (bh)#Activated"
];