export const Heads = [
   "3rd age full helmet",
   "3rd age mage hat",
   "3rd age range coif",
   "Adamant full helm",
   "Adamant med helm",
   "Ahrim's hood",
   "Ancestral hat",
   "Ancient ceremonial mask",
   "Ancient coif",
   "Ancient full helm",
   "Ancient halo",
   "Ancient mitre",
   "Arceuus hood",
   "Archer helm",
   "Ardougne knight helm",
   "Ardougne max hood",
   "Armadyl coif",
   "Armadyl full helm",
   "Armadyl halo",
   "Armadyl helmet",
   "Armadyl mitre",
   "Banana hat",
   "Bandos coif",
   "Bandos full helm",
   "Bandos halo",
   "Bandos mitre",
   "Banshee mask",
   "Beanie",
   "Bearhead",
   "Beekeeper's hat",
   "Beret mask",
   "Berserker helm",
   "Big pirate hat",
   "Black beret",
   "Black boater",
   "Black cavalier",
   "Black demon mask",
   "Black dragon mask",
   "Black full helm",
   "Black h'ween mask",
   "Black headband",
   "Black leprechaun hat",
   "Black mask (i)",
   "Black mask",
   "Black med helm",
   "Black partyhat",
   "Black santa hat",
   "Black tricorn hat",
   "Black unicorn mask",
   "Black wizard hat (g)",
   "Black wizard hat (t)",
   "Blacksmith's helm",
   "Blood'n'tar snelm (pointed)",
   "Blood'n'tar snelm (round)",
   "Bloodbark helm",
   "Blue beret",
   "Blue boater",
   "Blue dragon mask",
   "Blue halloween mask",
   "Blue hat",
   "Blue headband",
   "Blue partyhat",
   "Blue tricorn hat",
   "Blue wizard hat",
   "Bobble hat",
   "Bomber cap",
   "Bowl wig",
   "Brassica halo",
   "Broken bark snelm",
   "Bronze dragon mask",
   "Bronze full helm",
   "Bronze full helm (g)",
   "Bronze full helm (t)",
   "Bronze med helm",
   "Brown headband",
   "Brown tricorn hat",
   "Bruise blue snelm (pointed)",
   "Bruise blue snelm (round)",
   "Bucket helm",
   "Bucket helm (g)",
   "Bunny ears",
   "Bunnyman mask",
   "Cake hat",
   "Camel mask",
   "Camo helmet",
   "Cap and goggles",
   "Carpenter's helmet",
   "Cat mask",
   "Cavalier mask",
   "Chef's hat",
   "Chicken head",
   "Circlet of water",
   "Clown mask",
   "Coif",
   "Corrupted helm",
   "Corrupted helm (attuned)",
   "Corrupted helm (basic)",
   "Corrupted helm (perfected)",
   "Corrupted morrigan's coif (bh)",
   "Corrupted statius's full helm (bh)",
   "Corrupted zuriel's hood (bh)",
   "Cow mask",
   "Crab helmet",
   "Cream hat",
   "Crier hat",
   "Crystal helm (attuned)",
   "Crystal helm (basic)",
   "Crystal helm (perfected)",
   "Crystal helm",
   "Cyclops head",
   "Dagon'hai hat",
   "Dark cavalier",
   "Dark infinity hat",
   "Deerstalker",
   "Desert disguise",
   "Dharok's helm",
   "Doctor's hat",
   "Double eye patch",
   "Dragon full helm",
   "Dragon full helm (g)",
   "Dragon med helm",
   "Dragon med helm (cr)",
   "Dragonstone full helm",
   "Druidic wreath",
   "Dwarven helmet",
   "Earmuffs",
   "Easter egg helm",
   "Easter hat",
   "Elder chaos hood",
   "Elder chaos hood (or)",
   "Elemental helmet",
   "Enchanted hat",
   "Evil chicken head",
   "Facemask",
   "Fake beak",
   "Farseer helm",
   "Fedora",
   "Festive elf hat",
   "Festive games crown",
   "Fez",
   "Fighter hat",
   "Fishbowl helmet",
   "Five barrels",
   "Forestry hat",
   "Four barrels",
   "Fremennik hat",
   "Fremennik helm",
   "Frog mask",
   "Gas mask",
   "Giant boot",
   "Gilded coif",
   "Gilded full helm",
   "Gilded med helm",
   "Gnome child hat",
   "Gnome child mask",
   "Gnome goggles",
   "Goblin mask",
   "Gold headband",
   "Gold helmet",
   "Golden chef's hat",
   "Golden prospector helmet",
   "Graahk headdress",
   "Granite helm",
   "Gravedigger mask",
   "Greater demon mask",
   "Green boater",
   "Green dragon mask",
   "Green halloween mask",
   "Green hat",
   "Green headband",
   "Green partyhat",
   "Green tricorn hat",
   "Grey hat",
   "Grey tricorn hat",
   "Group iron helm",
   "Guthan's helm",
   "Guthix coif",
   "Guthix full helm",
   "Guthix halo",
   "Guthix mitre",
   "Half moon spectacles",
   "Hard hat",
   "Hardcore group iron helm",
   "Hardcore ironman helm",
   "Hat eyepatch",
   "Headless head",
   "Healer hat#Broken",
   "Healer hat#Locked",
   "Healer hat#Normal",
   "Hell cat ears",
   "Helm of neitiznot",
   "Helm of neitiznot (or)",
   "Helm of raedwald",
   "Highwayman mask",
   "Hornwood helm",
   "Hunter's honour",
   "Icthlarin's hood (tier 5)",
   "Imp mask",
   "Infinity hat",
   "Initiate sallet",
   "Inquisitor's great helm",
   "Inverted santa hat",
   "Iron dragon mask",
   "Iron full helm",
   "Iron med helm",
   "Ironman helm",
   "Jack lantern mask",
   "Jester hat",
   "Jungle demon mask",
   "Justiciar faceguard",
   "Kandarin headgear 1",
   "Kandarin headgear 2",
   "Kandarin headgear 3",
   "Kandarin headgear 4",
   "Karil's coif",
   "Khazard helmet",
   "Kyatt hat",
   "Larupia hat",
   "Lava dragon mask",
   "Leather cowl",
   "Lederhosen hat",
   "Left eye patch",
   "Leprechaun hat",
   "Lesser demon mask",
   "Light infinity hat",
   "Lunar helm",
   "Magma helm",
   "Mask of balance",
   "Mask of ranul",
   "Mask of rebirth",
   "Masori mask",
   "Masori mask (f)",
   "Menaphite purple hat",
   "Menaphite red hat",
   "Mime mask",
   "Mind helmet",
   "Mithril dragon mask",
   "Mithril full helm",
   "Mithril med helm",
   "Monocle",
   "Moonclan hat",
   "Moonclan helm",
   "Morrigan's coif (bh)#",
   "Mudskipper hat",
   "Mummy's head",
   "Musketeer hat",
   "Myre snelm (pointed)",
   "Myre snelm (round)",
   "Mystic hat",
   "Navy cavalier",
   "Neitiznot faceguard",
   "Nose peg",
   "Nurse hat",
   "Obsidian helmet",
   "Odd spectacles",
   "Old demon mask",
   "One barrel",
   "Orange boater",
   "Ornate helm",
   "Penguin mask",
   "Pheasant hat",
   "Pink boater",
   "Pink hat",
   "Pink headband",
   "Pirate hat",
   "Pirate's hat",
   "Pith helmet",
   "Propeller hat",
   "Proselyte sallet",
   "Prospector helmet",
   "Purple boater",
   "Purple hat",
   "Purple partyhat",
   "Purple tricorn hat",
   "Rainbow partyhat",
   "Ram skull helm",
   "Ranger hat",
   "Red beret",
   "Red boater",
   "Red cavalier",
   "Red dragon mask",
   "Red halloween mask",
   "Red hat",
   "Red headband",
   "Red partyhat",
   "Red tricorn hat",
   "Reindeer hat",
   "Reinforced goggles",
   "Right eye patch",
   "Rock-shell helm",
   "Rogue mask",
   "Rogue's revenge",
   "Royal crown",
   "Rune dragon mask",
   "Rune full helm",
   "Rune med helm",
   "Runner hat",
   "Sagacious spectacles",
   "Samurai kasa",
   "Sandwich lady hat",
   "Santa hat",
   "Santa mask",
   "Saradomin coif",
   "Saradomin full helm",
   "Saradomin halo",
   "Saradomin mitre",
   "Saucepan",
   "Seren halo",
   "Serpentine helm",
   "Shaman mask",
   "Shayzien helm (5)",
   "Silly jester hat",
   "Silver partyhat",
   "Skeletal helm",
   "Skeleton mask",
   "Slayer helmet",
   "Slayer helmet (i)",
   "Sleeping cap",
   "Snakeskin bandana",
   "Snow goggles %26 hat",
   "Spined helm",
   "Spiny helmet",
   "Spirit angler headband",
   "Splitbark helm",
   "Star-face",
   "Statius's full helm (bh)",
   "Steel dragon mask",
   "Steel full helm",
   "Steel med helm",
   "Swampbark helm",
   "Tan cavalier",
   "Tanzanite helm",
   "Teal hat",
   "Three barrels",
   "Top hat",
   "Torag's helm",
   "Torva full helm",
   "Tri-jester hat",
   "Tribal mask (combat)",
   "Tribal mask (disease)",
   "Tribal mask (poison)",
   "Turquoise hat",
   "Two barrels",
   "Tyras helm",
   "Ultimate ironman helm",
   "Uri's hat",
   "Verac's helm",
   "Virtus mask",
   "Void mage helm",
   "Void melee helm",
   "Void ranger helm",
   "Warrior helm",
   "White beret",
   "White boater",
   "White cavalier",
   "White full helm",
   "White headband",
   "White med helm",
   "White partyhat",
   "White unicorn mask",
   "Wise old man's santa hat",
   "Witch hat",
   "Wizard hat",
   "Wolf mask",
   "Woolly hat",
   "Xerician hat",
   "Yellow hat",
   "Yellow partyhat",
   "Zamorak coif",
   "Zamorak full helm",
   "Zamorak halo#Broken",
   "Zamorak halo#Locked",
   "Zamorak halo#Normal",
   "Zamorak mitre",
   "Zealot's helm",
   "Zombie mask",
   "Zuriel's hood (bh)#Activated"
];