export const Legs = [
   "20th anniversary bottom",
   "3rd age druidic robe bottoms",
   "3rd age platelegs",
   "3rd age plateskirt",
   "3rd age range legs",
   "3rd age robe",
   "Adamant platelegs",
   "Adamant platelegs (g)",
   "Adamant platelegs (t)",
   "Adamant plateskirt",
   "Adamant plateskirt (g)",
   "Adamant plateskirt (t)",
   "Ahrim's robeskirt",
   "Ancestral robe bottom",
   "Ancient ceremonial legs",
   "Ancient chaps",
   "Ancient platelegs",
   "Ancient plateskirt",
   "Ancient robe legs",
   "Angler waders",
   "Ankou's leggings",
   "Antisanta pantaloons",
   "Ardougne knight platelegs",
   "Armadyl chainskirt",
   "Armadyl chaps",
   "Armadyl platelegs",
   "Armadyl plateskirt",
   "Armadyl robe legs",
   "Bandos chaps",
   "Bandos platelegs",
   "Bandos plateskirt",
   "Bandos robe legs",
   "Bandos tassets",
   "Banshee robe",
   "Beekeeper's legs",
   "Black d'hide chaps",
   "Black desert robe",
   "Black elegant legs",
   "Black navy slacks",
   "Black platelegs",
   "Black plateskirt",
   "Black skirt",
   "Black skirt (g)",
   "Black skirt (t)",
   "Bloodbark legs",
   "Blue d'hide chaps",
   "Blue elegant legs",
   "Blue elegant skirt",
   "Blue navy slacks",
   "Blue robe bottoms",
   "Blue skirt",
   "Blue skirt (g)",
   "Blue skirt (t)",
   "Bronze platelegs",
   "Bronze platelegs (g)",
   "Bronze platelegs (t)",
   "Bronze plateskirt",
   "Bronze plateskirt (g)",
   "Bronze plateskirt (t)",
   "Brown navy slacks",
   "Builder's trousers",
   "Bunny legs",
   "Camo bottoms",
   "Carpenter's trousers",
   "Chicken legs",
   "Citizen trousers",
   "Clue hunter trousers",
   "Corrupted legs (attuned)",
   "Corrupted legs (basic)",
   "Corrupted legs (perfected)",
   "Corrupted morrigan's leather chaps (bh)#Activated",
   "Corrupted platelegs",
   "Corrupted plateskirt",
   "Corrupted statius's platelegs (bh)#Activated",
   "Corrupted vesta's plateskirt (bh)#Activated",
   "Corrupted zuriel's robe bottom (bh)#Activated",
   "Cow trousers",
   "Cream robe bottoms",
   "Crystal legs (Amlodd)#Active",
   "Crystal legs (Amlodd)#Inactive",
   "Crystal legs (Cadarn)#Active",
   "Crystal legs (Cadarn)#Inactive",
   "Crystal legs (Crwys)#Active",
   "Crystal legs (Crwys)#Inactive",
   "Crystal legs (Hefin)#Active",
   "Crystal legs (Hefin)#Inactive",
   "Crystal legs (Iorwerth)#Active",
   "Crystal legs (Iorwerth)#Inactive",
   "Crystal legs (Ithell)#Active",
   "Crystal legs (Ithell)#Inactive",
   "Crystal legs (Trahaearn)#Active",
   "Crystal legs (Trahaearn)#Inactive",
   "Crystal legs (attuned)",
   "Crystal legs (basic)",
   "Crystal legs (perfected)",
   "Crystal legs#Active",
   "Crystal legs#Inactive",
   "Dagon'hai robe bottom",
   "Dark infinity bottoms",
   "Dark trousers",
   "Desert camo legs",
   "Desert legs",
   "Desert robe",
   "Desert robes",
   "Dharok's platelegs",
   "Dragon platelegs",
   "Dragon platelegs (cr)",
   "Dragon platelegs (g)",
   "Dragon plateskirt",
   "Dragon plateskirt (cr)",
   "Dragon plateskirt (g)",
   "Dragonstone platelegs",
   "Druid's robe",
   "Eggshell platelegs",
   "Elder chaos robe",
   "Elder chaos robe (or)",
   "Elite void robe",
   "Elven legwear",
   "Elven skirt (white)",
   "Elven skirt (yellow)",
   "Enchanted robe",
   "Evil chicken legs",
   "Flared trousers",
   "Forestry legs",
   "Fremennik kilt",
   "Fremennik skirt",
   "Frog-leather chaps",
   "Ghostly robe (bottom)",
   "Gilded d'hide chaps",
   "Gilded platelegs",
   "Gilded plateskirt",
   "Gold elegant legs",
   "Gold elegant skirt",
   "Golden prospector legs",
   "Graahk legs",
   "Granite legs",
   "Green d'hide chaps",
   "Green d'hide chaps (g)",
   "Green d'hide chaps (t)",
   "Green elegant legs",
   "Green elegant skirt",
   "Green navy slacks",
   "Green robe bottoms",
   "Grey navy slacks",
   "Grey robe bottoms",
   "Group iron platelegs",
   "Group iron platelegs (unranked)",
   "Guthan's chainskirt",
   "Guthix chaps",
   "Guthix platelegs",
   "Guthix plateskirt",
   "Guthix robe legs",
   "Ham robe",
   "Hardcore group iron platelegs",
   "Hardcore ironman platelegs",
   "Infinity bottoms",
   "Initiate cuisse",
   "Inquisitor's plateskirt",
   "Iron platelegs",
   "Iron platelegs (g)",
   "Iron platelegs (t)",
   "Iron plateskirt",
   "Iron plateskirt (g)",
   "Iron plateskirt (t)",
   "Ironman platelegs",
   "Jungle camo legs",
   "Justiciar legguards",
   "Karil's leatherskirt",
   "Kyatt legs",
   "Larupia legs",
   "Leather chaps",
   "Leather chaps (g)",
   "Lederhosen shorts",
   "Light infinity bottoms",
   "Light trousers",
   "Lumberjack legs",
   "Lunar legs",
   "Masori chaps",
   "Masori chaps (f)",
   "Menaphite purple kilt",
   "Menaphite purple robe",
   "Menaphite red kilt",
   "Menaphite red robe",
   "Mime legs",
   "Mithril platelegs",
   "Mithril platelegs (g)",
   "Mithril platelegs (t)",
   "Mithril plateskirt",
   "Mithril plateskirt (g)",
   "Mithril plateskirt (t)",
   "Monk's robe",
   "Monk's robe (g)",
   "Monk's robe (t)",
   "Moonclan skirt",
   "Morrigan's leather chaps (bh)#Activated",
   "Morytania legs 1",
   "Morytania legs 2",
   "Morytania legs 3",
   "Morytania legs 4",
   "Mourner trousers",
   "Mummy's legs",
   "Musketeer pants",
   "Mystic robe bottom",
   "Obsidian platelegs",
   "Ornate legs",
   "Pantaloons",
   "Penance skirt",
   "Pheasant legs",
   "Pink elegant legs",
   "Pink elegant skirt",
   "Pink robe bottoms",
   "Pink skirt",
   "Pirate leggings (beige)",
   "Pirate leggings (blue)",
   "Pirate leggings (brown)",
   "Pirate leggings (red)",
   "Plague trousers",
   "Polar camo legs",
   "Priest gown (bottom)",
   "Prince leggings",
   "Princess skirt",
   "Proselyte cuisse",
   "Proselyte tasset",
   "Prospector legs",
   "Purple elegant legs",
   "Purple elegant skirt",
   "Purple navy slacks",
   "Purple robe bottoms",
   "Pyromancer robe",
   "Rangers' tights",
   "Red d'hide chaps",
   "Red d'hide chaps (g)",
   "Red d'hide chaps (t)",
   "Red elegant legs",
   "Red elegant skirt",
   "Red navy slacks",
   "Red robe bottoms",
   "Robe bottom of darkness",
   "Robe bottom of ruin",
   "Robe bottoms of the eye",
   "Robe of elidinis (bottom)",
   "Rock-shell legs",
   "Rogue trousers",
   "Royal gown bottom",
   "Rune platelegs",
   "Rune platelegs (g)",
   "Rune platelegs (t)",
   "Rune plateskirt",
   "Rune plateskirt (g)",
   "Rune plateskirt (t)",
   "Samurai greaves",
   "Sandwich lady bottom",
   "Sanguine torva platelegs",
   "Santa pantaloons",
   "Saradomin chaps",
   "Saradomin platelegs",
   "Saradomin plateskirt",
   "Saradomin robe legs",
   "Shade robe",
   "Shayzien greaves (5)",
   "Shorts (blue)",
   "Shorts (brown)",
   "Shorts (yellow)",
   "Silly jester tights",
   "Skeletal bottoms",
   "Skeleton leggings",
   "Skirt (blue)",
   "Skirt (brown)",
   "Skirt (lilac)",
   "Slave robe",
   "Smiths trousers",
   "Snakeskin chaps",
   "Spined chaps",
   "Spirit angler waders",
   "Splitbark legs",
   "Spookier skirt",
   "Spooky skirt#Reward",
   "Statius's platelegs (bh)",
   "Steel platelegs",
   "Steel plateskirt",
   "Studded chaps",
   "Studded chaps (g)",
   "Studded chaps (t)",
   "Swampbark legs",
   "Teal robe bottoms",
   "Torag's platelegs",
   "Torva platelegs",
   "Tree skirt",
   "Trousers (blue)",
   "Trousers (brown)",
   "Trousers (lilac)",
   "Turquoise robe bottoms",
   "Twisted ancestral robe bottom",
   "Twisted trousers (t1)",
   "Twisted trousers (t2)",
   "Twisted trousers (t3)",
   "Verac's plateskirt",
   "Vesta's plateskirt (bh)",
   "Villager robe (blue)",
   "Villager robe (brown)",
   "Villager robe (pink)",
   "Villager robe (yellow)",
   "Virtus robe bottom",
   "Void knight robe",
   "Vyre noble coat tails (grey)",
   "Vyre noble coat tails (purple)",
   "Vyre noble coat tails (red)",
   "Vyre noble dress bottom (grey)",
   "Vyre noble dress bottom (purple)",
   "Vyre noble dress bottom (red)",
   "Vyre noble legs",
   "Vyre noble pants (grey)",
   "Vyre noble pants (purple)",
   "Vyre noble pants (red)",
   "Vyre noble skirt (grey)",
   "Vyre noble skirt (purple)",
   "Vyre noble skirt (red)",
   "Vyrewatch legs",
   "White elegant skirt",
   "White platelegs",
   "White plateskirt",
   "Witch robes",
   "Wood camo legs",
   "Xerician robe",
   "Yak-hide armour (legs)",
   "Yellow robe bottoms",
   "Zamorak chaps",
   "Zamorak monk bottom",
   "Zamorak platelegs",
   "Zamorak plateskirt",
   "Zamorak robe legs",
   "Zealot's robe bottom",
   "Zombie trousers",
   "Zuriel's robe bottom (bh)"
];