export const Necks = [
   "3rd age amulet",
   "Amulet of accuracy",
   "Amulet of avarice",
   "Amulet of blood fury",
   "Amulet of bounty",
   "Amulet of chemistry",
   "Amulet of defence",
   "Amulet of defence (t)",
   "Amulet of eternal glory",
   "Amulet of fury",
   "Amulet of fury (or)",
   "Amulet of glory (t)",
   "Amulet of glory",
   "Amulet of magic",
   "Amulet of magic (t)",
   "Amulet of nature",
   "Amulet of power",
   "Amulet of power (t)",
   "Amulet of strength",
   "Amulet of the damned",
   "Amulet of torture",
   "Amulet of torture (or)",
   "Ancient stole",
   "Arceuus scarf",
   "Armadyl pendant",
   "Armadyl stole",
   "Bandos stole",
   "Beads of the dead",
   "Berserker necklace",
   "Binding necklace",
   "Bobble scarf",
   "Bonecrusher necklace",
   "Brass necklace",
   "Clean necklace",
   "Crone-made amulet",
   "Crystal pendant",
   "Dark bow tie",
   "Desert amulet 1",
   "Desert amulet 2",
   "Desert amulet 3",
   "Desert amulet 4",
   "Diamond amulet",
   "Diamond necklace",
   "Dodgy necklace",
   "Dragon necklace",
   "Dragonbone necklace",
   "Glarial's amulet",
   "Globetrotter pendant",
   "Gnome amulet",
   "Gnome scarf",
   "Gold amulet",
   "Gold necklace",
   "Guthix stole",
   "Hallowed symbol",
   "Ham logo",
   "Hazeel's mark",
   "Holy symbol",
   "Hosidius scarf",
   "Jade amulet",
   "Jade necklace",
   "Jester scarf",
   "Light bow tie",
   "Lunar amulet",
   "Necklace of anguish",
   "Necklace of anguish (or)",
   "Occult necklace",
   "Occult necklace (or)",
   "Onyx amulet",
   "Onyx necklace",
   "Opal amulet",
   "Opal necklace",
   "Pendant of lucien",
   "Petal garland",
   "Phoenix necklace",
   "Piscarilius scarf",
   "Pre-nature amulet",
   "Ruby amulet",
   "Ruby necklace",
   "Salve amulet",
   "Salve amulet (e)",
   "Salve amulet(ei)",
   "Sapphire amulet",
   "Sapphire necklace",
   "Saradomin stole",
   "Seal of passage",
   "Shayzien scarf",
   "Skills necklace",
   "Strength amulet (t)",
   "Strung rabbit foot",
   "Tarnished locket",
   "Topaz amulet",
   "Topaz necklace",
   "Tri-jester scarf",
   "Unblessed symbol",
   "Unholy symbol",
   "Unpowered symbol",
   "Void seal",
   "Witchwood icon",
   "Zamorak stole",
   "Zenyte amulet",
   "Zenyte necklace",
   "'perfect' necklace"
];