export const Rings = [
   "Archers ring",
   "Archers ring (i)",
   "Beacon ring",
   "Bellator ring",
   "Berserker ring",
   "Berserker ring (i)",
   "Brimstone ring",
   "Celestial ring",
   "Celestial signet",
   "Crate ring",
   "Diamond ring",
   "Dragonstone ring",
   "Easter ring",
   "Efaritay's aid",
   "Elven signet",
   "Emerald ring",
   "Escape crystal",
   "Explorer's ring 1",
   "Explorer's ring 2",
   "Explorer's ring 3",
   "Explorer's ring 4",
   "Gold ring",
   "Granite ring",
   "Granite ring (i)",
   "Hallowed ring",
   "Jade ring",
   "Lightbearer",
   "Lunar ring",
   "Magus ring",
   "Onyx ring",
   "Opal ring",
   "Ring of 3rd age",
   "Ring of charos",
   "Ring of coins",
   "Ring of endurance",
   "Ring of forging",
   "Ring of life",
   "Ring of nature",
   "Ring of pursuit",
   "Ring of recoil",
   "Ring of returning",
   "Ring of shadows",
   "Ring of stone",
   "Ring of suffering (i)",
   "Ring of suffering",
   "Ring of the elements",
   "Ring of the gods",
   "Ring of the gods (i)",
   "Ring of visibility",
   "Ring of wealth (i)",
   "Ruby ring",
   "Sapphire ring",
   "Seers ring",
   "Seers ring (i)",
   "Slayer ring (eternal)",
   "Slayer ring",
   "Snowman ring",
   "Topaz ring",
   "Treasonous ring",
   "Treasonous ring (i)",
   "Tyrannical ring",
   "Tyrannical ring (i)",
   "Ultor ring",
   "Venator ring",
   "Warrior ring",
   "Warrior ring (i)",
   "Zenyte ring",
   "'perfect' ring"
];