export const Shields = [
   "3rd age kiteshield",
   "Adamant defender",
   "Adamant kiteshield",
   "Adamant sq shield",
   "Ancient d'hide shield",
   "Ancient kiteshield",
   "Ancient wyvern shield",
   "Anti-dragon shield",
   "Arcane grimoire",
   "Arcane spirit shield",
   "Armadyl d'hide shield",
   "Armadyl kiteshield",
   "Avernic defender",
   "Bandos d'hide shield",
   "Bandos kiteshield",
   "Black d'hide shield",
   "Black defender",
   "Black kiteshield",
   "Black satchel",
   "Black sq shield",
   "Blessed spirit shield",
   "Blue d'hide shield",
   "Blue gingerbread shield",
   "Book of balance",
   "Book of balance (or)",
   "Book of darkness",
   "Book of darkness (or)",
   "Book of law",
   "Book of law (or)",
   "Book of the dead",
   "Book of war",
   "Book of war (or)",
   "Briefcase",
   "Bronze defender",
   "Bronze kiteshield",
   "Bronze sq shield",
   "Broodoo shield (combat)#(1)",
   "Broodoo shield (combat)#(10)",
   "Broodoo shield (combat)#(2)",
   "Broodoo shield (combat)#(3)",
   "Broodoo shield (combat)#(4)",
   "Broodoo shield (combat)#(5)",
   "Broodoo shield (combat)#(6)",
   "Broodoo shield (combat)#(7)",
   "Broodoo shield (combat)#(8)",
   "Broodoo shield (combat)#(9)",
   "Broodoo shield (combat)#Uncharged",
   "Broodoo shield (disease)#(1)",
   "Broodoo shield (disease)#(10)",
   "Broodoo shield (disease)#(2)",
   "Broodoo shield (disease)#(3)",
   "Broodoo shield (disease)#(4)",
   "Broodoo shield (disease)#(5)",
   "Broodoo shield (disease)#(6)",
   "Broodoo shield (disease)#(7)",
   "Broodoo shield (disease)#(8)",
   "Broodoo shield (disease)#(9)",
   "Broodoo shield (disease)#Uncharged",
   "Broodoo shield (poison)#(1)",
   "Broodoo shield (poison)#(10)",
   "Broodoo shield (poison)#(2)",
   "Broodoo shield (poison)#(3)",
   "Broodoo shield (poison)#(4)",
   "Broodoo shield (poison)#(5)",
   "Broodoo shield (poison)#(6)",
   "Broodoo shield (poison)#(7)",
   "Broodoo shield (poison)#(8)",
   "Broodoo shield (poison)#(9)",
   "Broodoo shield (poison)#Uncharged",
   "Cabbage round shield",
   "Chronicle",
   "Corrupted kiteshield",
   "Cruciferous codex",
   "Crystal shield#Active",
   "Crystal shield#Inactive",
   "Crystal shield#New",
   "Damaged book (Ancient)",
   "Damaged book (Armadyl)",
   "Damaged book (Bandos)",
   "Damaged book (Guthix)",
   "Damaged book (Saradomin)",
   "Damaged book (Zamorak)",
   "Decorative shield (gold)",
   "Decorative shield (red)",
   "Decorative shield (white)",
   "Dragon defender (t)",
   "Dragon defender",
   "Dragon kiteshield",
   "Dragon kiteshield (g)",
   "Dragon sq shield",
   "Dragon sq shield (cr)",
   "Dragon sq shield (g)",
   "Dragonfire shield",
   "Dragonfire ward",
   "Elemental shield",
   "Elidinis' ward",
   "Elidinis' ward (f)",
   "Elidinis' ward (or)",
   "Elysian spirit shield",
   "Fairy mushroom",
   "Falador shield 1",
   "Falador shield 2",
   "Falador shield 3",
   "Falador shield 4",
   "Fremennik shield",
   "Ghommal's avernic defender 5",
   "Ghommal's avernic defender 6",
   "Ghommal's hilt 1",
   "Ghommal's hilt 2",
   "Ghommal's hilt 3",
   "Ghommal's hilt 4",
   "Ghommal's hilt 5",
   "Ghommal's hilt 6",
   "Gilded kiteshield",
   "Gilded sq shield",
   "Gnome child plush",
   "Gold satchel",
   "Granite shield",
   "Green d'hide shield",
   "Green gingerbread shield",
   "Green satchel",
   "Guthix d'hide shield",
   "Guthix kiteshield",
   "Hallowed focus",
   "Hard leather shield",
   "Holy book",
   "Holy book (or)",
   "Iron defender",
   "Iron kiteshield",
   "Iron kiteshield (g)",
   "Iron kiteshield (t)",
   "Iron sq shield",
   "Jad plush",
   "Kharedst's memoirs",
   "Mage's book",
   "Magic lantern",
   "Magic shield",
   "Malediction ward",
   "Malediction ward (or)",
   "Maple shield",
   "Mind shield",
   "Mirror shield",
   "Mithril defender",
   "Mithril kiteshield",
   "Mithril kiteshield (g)",
   "Mithril kiteshield (t)",
   "Mithril sq shield",
   "Neitiznot shield",
   "Oak shield",
   "Odium ward",
   "Odium ward (or)",
   "Plain satchel",
   "Pumpkin lantern",
   "Red d'hide shield",
   "Red gingerbread shield",
   "Red satchel",
   "Redwood shield",
   "Ruinous powers (item)",
   "Rune defender (t)",
   "Rune defender",
   "Rune kiteshield",
   "Rune satchel",
   "Rune sq shield",
   "Saradomin d'hide shield",
   "Saradomin kiteshield",
   "Snakeskin shield",
   "Spectral spirit shield",
   "Spirit shield",
   "Steel defender#Broken",
   "Steel defender#Locked",
   "Steel defender#Normal",
   "Steel kiteshield",
   "Steel sq shield",
   "Stray dog plush",
   "Toktz-ket-xil",
   "Tome of fire",
   "Tome of water",
   "Training shield",
   "Twisted buckler",
   "Unholy book",
   "Unholy book (or)",
   "V's shield",
   "White kiteshield",
   "White sq shield",
   "Willow shield",
   "Wooden shield",
   "Wooden shield (g)",
   "Yew shield",
   "Zamorak d'hide shield",
   "Zamorak kiteshield"
];