export const TwoHandeds = [
   "3rd age bow",
   "3rd age felling axe",
   "Abyssal bludgeon",
   "Adamant 2h sword",
   "Adamant claws",
   "Adamant felling axe",
   "Adamant halberd",
   "Adamant spear",
   "Ancient godsword",
   "Anger spear",
   "Armadyl godsword",
   "Armadyl godsword (or)",
   "Bandos godsword",
   "Bandos godsword (or)",
   "Barrelchest anchor (bh)",
   "Barrelchest anchor",
   "Birthday cake",
   "Black 2h sword",
   "Black claws",
   "Black felling axe",
   "Black halberd",
   "Black salamander",
   "Black spear",
   "Blazing blowpipe",
   "Bow of faerdhinen",
   "Bronze 2h sword",
   "Bronze claws",
   "Bronze felling axe",
   "Bronze halberd",
   "Bronze spear",
   "Clueless scroll",
   "Colossal blade",
   "Comp ogre bow",
   "Corrupted armadyl godsword",
   "Corrupted bow (attuned)",
   "Corrupted bow (basic)",
   "Corrupted bow (perfected)",
   "Corrupted dragon claws",
   "Corrupted halberd (attuned)",
   "Corrupted halberd (basic)",
   "Corrupted halberd (perfected)",
   "Corrupted staff (attuned)",
   "Corrupted staff (basic)",
   "Corrupted staff (perfected)",
   "Corrupted tumeken's shadow",
   "Corrupted twisted bow",
   "Crate with zanik",
   "Craw's bow#Charged",
   "Craw's bow#Uncharged",
   "Crystal bow (attuned)",
   "Crystal bow (basic)",
   "Crystal bow (perfected)",
   "Crystal bow",
   "Crystal felling axe",
   "Crystal halberd (attuned)",
   "Crystal halberd (basic)",
   "Crystal halberd (perfected)",
   "Crystal halberd",
   "Crystal staff (attuned)",
   "Crystal staff (basic)",
   "Crystal staff (perfected)",
   "Cursed banana",
   "Cursed goblin bow",
   "Dark bow (bh)",
   "Dark bow",
   "Defensive shield",
   "Dharok's greataxe",
   "Dinh's blazing bulwark",
   "Dinh's bulwark",
   "Dragon 2h sword",
   "Dragon 2h sword (cr)",
   "Dragon claws",
   "Dragon claws (cr)",
   "Dragon claws (or)",
   "Dragon felling axe",
   "Dragon halberd",
   "Dragon halberd (cr)",
   "Dragon spear (cr)",
   "Dragon spear",
   "Dual sai",
   "Elder maul",
   "Elder maul (or)",
   "Fixed device",
   "Gadderhammer",
   "Giant boulder",
   "Giant bronze dagger",
   "Giant present",
   "Giant stopwatch",
   "Gilded 2h sword",
   "Gilded spade",
   "Gilded spear",
   "Goblin paint cannon",
   "Granite maul",
   "Gregg's eastdoor",
   "Guthan's warspear",
   "Guthix mjolnir",
   "Heavy ballista",
   "Heavy ballista (or)",
   "Heavy casket",
   "Hill giant club",
   "Iron 2h sword",
   "Iron claws",
   "Iron felling axe",
   "Iron halberd",
   "Iron spear",
   "Karil's crossbow",
   "Katana",
   "Large spade",
   "Leaf-bladed spear",
   "Light ballista",
   "Longbow",
   "Love crossbow",
   "Magic comp bow",
   "Magic longbow",
   "Magic shortbow",
   "Magic shortbow (i)",
   "Maple longbow",
   "Maple shortbow",
   "Merfolk trident",
   "Mithril 2h sword",
   "Mithril claws",
   "Mithril felling axe",
   "Mithril halberd",
   "Mithril spear",
   "Mystic cards",
   "Nunchaku",
   "Oak longbow",
   "Oak shortbow",
   "Ogre bow",
   "Orange salamander",
   "Preform",
   "Pugel",
   "Red salamander",
   "Rune 2h sword",
   "Rune claws",
   "Rune felling axe",
   "Rune halberd",
   "Rune spear",
   "Saradomin godsword",
   "Saradomin godsword (or)",
   "Saradomin mjolnir",
   "Saradomin sword",
   "Saradomin's blessed sword",
   "Scythe of vitur",
   "Seercull",
   "Shadow sword",
   "Silver speedrun trophy",
   "Skeleton lantern",
   "Soulreaper axe",
   "Spatula",
   "Starter bow",
   "Steel 2h sword",
   "Steel claws",
   "Steel felling axe",
   "Steel halberd",
   "Steel spearx",
   "Swamp lizard",
   "Toktz-mej-tal",
   "Torag's hammers",
   "Toxic blowpipe",
   "Training bow",
   "Tumeken's shadow",
   "Twisted adamant trophy",
   "Twisted bow",
   "Twisted dragon trophy",
   "Twisted rune trophy",
   "Tzhaar-ket-om",
   "Venator bow#Charged",
   "Venator bow#Uncharged",
   "Verac's flail",
   "Vesta's spear (bh)",
   "Webweaver bow",
   "White 2h sword",
   "White claws",
   "White halberd",
   "Willow comp bow",
   "Willow longbow",
   "Willow shortbow",
   "Yew comp bow",
   "Yew longbow",
   "Yew shortbow",
   "Zamorak godsword",
   "Zamorak godsword (or)",
   "Zamorak mjolnir",
   "Zamorakian spear",
];