export const Weapons = [
   "3rd age axe",
   "3rd age druidic staff",
   "3rd age longsword",
   "3rd age pickaxe",
   "3rd age wand",
   "Abyssal dagger (bh)",
   "Abyssal dagger",
   "Abyssal tentacle",
   "Abyssal tentacle (or)",
   "Abyssal whip",
   "Abyssal whip (or)",
   "Accursed sceptre (a)",
   "Accursed sceptre",
   "Adamant axe",
   "Adamant battleaxe",
   "Adamant cane",
   "Adamant crossbow",
   "Adamant dagger",
   "Adamant dart",
   "Adamant hasta",
   "Adamant knife",
   "Adamant longsword",
   "Adamant mace",
   "Adamant pickaxe",
   "Adamant scimitar",
   "Adamant sword",
   "Adamant thrownaxe",
   "Adamant warhammer",
   "Ahrim's staff",
   "Air battlestaff",
   "Ale of the gods",
   "Amethyst dart",
   "Amy's saw",
   "Ancient crozier",
   "Ancient mace",
   "Ancient sceptre",
   "Ancient staff",
   "Anger battleaxe",
   "Anger mace",
   "Anger sword",
   "Apprentice wand",
   "Arceuus banner",
   "Arclight",
   "Armadyl crossbow",
   "Armadyl crozier",
   "Assorted flowers",
   "Bandos crozier",
   "Barb-tail harpoon",
   "Barronite mace",
   "Battlestaff",
   "Beginner wand",
   "Birthday balloons",
   "Black axe",
   "Black battleaxe",
   "Black cane",
   "Black chinchompa",
   "Black dagger",
   "Black dart",
   "Black flowers",
   "Black knife",
   "Black longsword",
   "Black mace",
   "Black pickaxe",
   "Black scimitar",
   "Black sword",
   "Black warhammer",
   "Blade of saeldor (c)",
   "Blessed axe",
   "Blisterwood flail",
   "Blisterwood sickle",
   "Blood ancient sceptre",
   "Blue flowers",
   "Blurite crossbow",
   "Blurite sword",
   "Bone club",
   "Bone dagger",
   "Bone spear",
   "Brine sabre",
   "Bronze axe",
   "Bronze battleaxe",
   "Bronze crossbow",
   "Bronze dagger",
   "Bronze dart",
   "Bronze fist flag",
   "Bronze hasta",
   "Bronze knife",
   "Bronze longsword",
   "Bronze mace",
   "Bronze pickaxe",
   "Bronze scimitar",
   "Bronze sword",
   "Bronze thrownaxe",
   "Bronze warhammer",
   "Bruma torch",
   "Bryophyta's staff",
   "Butterfly net",
   "Candy cane",
   "Carrot sword",
   "Cattleprod",
   "Chaotic handegg",
   "Chinchompa",
   "Cleaver",
   "Cormorant's glove",
   "Corrupted axe",
   "Corrupted harpoon",
   "Corrupted pickaxe",
   "Corrupted sceptre",
   "Crier bell",
   "Crossbow",
   "Crystal axe",
   "Crystal grail",
   "Crystal harpoon",
   "Crystal pickaxe",
   "Crystal sceptre",
   "Cursed goblin hammer",
   "Cursed goblin staff",
   "Cutthroat flag",
   "Dark dagger",
   "Darklight",
   "Dawnbringer",
   "Dorgeshuun crossbow",
   "Dragon axe",
   "Dragon axe (or)",
   "Dragon battleaxe",
   "Dragon battleaxe (cr)",
   "Dragon candle dagger",
   "Dragon cane",
   "Dragon crossbow",
   "Dragon crossbow (cr)",
   "Dragon dagger (cr)",
   "Dragon dagger",
   "Dragon dart",
   "Dragon harpoon",
   "Dragon harpoon (or)",
   "Dragon hasta",
   "Dragon hunter crossbow",
   "Dragon hunter lance",
   "Dragon knife",
   "Dragon longsword",
   "Dragon longsword (bh)",
   "Dragon longsword (cr)",
   "Dragon mace",
   "Dragon mace (bh)",
   "Dragon mace (cr)",
   "Dragon pickaxe",
   "Dragon pickaxe (or)",
   "Dragon pickaxe (upgraded)",
   "Dragon scimitar",
   "Dragon scimitar (cr)",
   "Dragon scimitar (or)",
   "Dragon sword",
   "Dragon sword (cr)",
   "Dragon thrownaxe",
   "Dragon warhammer",
   "Dragon warhammer (cr)",
   "Dramen staff",
   "Dust battlestaff",
   "Earth battlestaff",
   "Easter basket",
   "Eek#Reward",
   "Egg whisk",
   "Eldritch nightmare staff",
   "Emerald sickle (b)",
   "Enchanted emerald sickle (b)",
   "Enchanted lyre(i)",
   "Enchanted ruby sickle (b)",
   "Excalibur",
   "Fire battlestaff",
   "Fremennik blade",
   "Frozen abyssal whip",
   "Frying pan",
   "Ghrazi rapier",
   "Gilded axe",
   "Gilded hasta",
   "Gilded pickaxe",
   "Gilded scimitar",
   "Gilded smile flag",
   "Glowing dagger",
   "Gnomeball",
   "Golden tench",
   "Granite hammer",
   "Granite longsword",
   "Guthix crozier",
   "Guthix staff",
   "Hallowed hammer",
   "Ham joint",
   "Hand fan",
   "Harmonised nightmare staff",
   "Harry's cutlass",
   "Haunted wine bottle",
   "Heat-proof vessel",
   "Holy ghrazi rapier",
   "Holy handegg",
   "Holy water",
   "Hunters' crossbow",
   "Hunting knife",
   "Iban's staff (u)",
   "Iban's staff",
   "Ice ancient sceptre",
   "Imbued tephra",
   "Infernal axe (or)",
   "Infernal axe",
   "Infernal harpoon (or)",
   "Infernal harpoon",
   "Infernal pickaxe (or)",
   "Infernal pickaxe",
   "Inquisitor's mace",
   "Iron axe",
   "Iron battleaxe",
   "Iron crossbow",
   "Iron dagger",
   "Iron dart",
   "Iron hasta",
   "Iron knife",
   "Iron longsword",
   "Iron mace",
   "Iron pickaxe",
   "Iron pickaxe (nz)",
   "Iron scimitar",
   "Iron sickle",
   "Iron sword",
   "Iron thrownaxe",
   "Iron warhammer",
   "Ivandis flail",
   "Jade machete",
   "Keris partisan",
   "Keris partisan of breaching",
   "Keris partisan of corruption",
   "Keris partisan of the sun",
   "Keris",
   "Kodai wand",
   "Lava battlestaff",
   "Lava battlestaff (or)",
   "Leaf-bladed battleaxe",
   "Leaf-bladed sword",
   "Lucky cutlass",
   "Lucky shot flag",
   "Lunar staff",
   "Lyre",
   "Machete",
   "Magic butterfly net",
   "Magic secateurs",
   "Magic staff",
   "Maple blackjack",
   "Maple blackjack(d)",
   "Maple blackjack(o)",
   "Master wand",
   "Meat tenderiser",
   "Mist battlestaff",
   "Mithril axe",
   "Mithril battleaxe",
   "Mithril crossbow",
   "Mithril dagger",
   "Mithril dart",
   "Mithril hasta",
   "Mithril knife",
   "Mithril longsword",
   "Mithril mace",
   "Mithril pickaxe",
   "Mithril scimitar",
   "Mithril sword",
   "Mithril thrownaxe",
   "Mithril warhammer",
   "Mixed flowers",
   "Monkey talisman",
   "Morrigan's javelin (bh)",
   "Morrigan's throwing axe (bh)",
   "Mouse toy",
   "Mud battlestaff",
   "Mud pie",
   "Mystic air staff",
   "Mystic dust staff",
   "Mystic earth staff",
   "Mystic fire staff",
   "Mystic lava staff",
   "Mystic lava staff (or)",
   "Mystic mist staff",
   "Mystic mud staff",
   "Mystic smoke staff",
   "Mystic steam staff",
   "Mystic steam staff (or)",
   "Mystic water staff",
   "Nightmare staff",
   "Noose wand",
   "Oak blackjack",
   "Oak blackjack(d)",
   "Oak blackjack(o)",
   "Oily pearl fishing rod",
   "Opal machete",
   "Orange flowers",
   "Osmumten's fang",
   "Osmumten's fang (or)",
   "Peaceful handegg",
   "Pearl barbarian rod",
   "Pearl fishing rod",
   "Pearl fly fishing rod",
   "Pharaoh's sceptre",
   "Phasmatys flag",
   "Phoenix crossbow",
   "Prop sword",
   "Purple flowers",
   "Rapier",
   "Red chinchompa",
   "Red flowers",
   "Red topaz machete",
   "Rod of ivandis",
   "Rolling pin",
   "Royal sceptre",
   "Rubber chicken",
   "Ruby sickle (b)",
   "Rune axe",
   "Rune battleaxe",
   "Rune cane",
   "Rune crossbow",
   "Rune crossbow (or)",
   "Rune dagger",
   "Rune dart#",
   "Rune hasta",
   "Rune knife",
   "Rune longsword",
   "Rune mace",
   "Rune pickaxe",
   "Rune pickaxe (nz)",
   "Rune scimitar",
   "Rune sword",
   "Rune thrownaxe",
   "Rune warhammer",
   "Sage's axe",
   "Sanguinesti staff",
   "Sarachnis cudgel",
   "Saradomin crozier",
   "Saradomin staff",
   "Severed leg",
   "Shadow ancient sceptre",
   "Shattered cane",
   "Silver sickle",
   "Silver sickle (b)",
   "Silverlight",
   "Skewer",
   "Skull sceptre",
   "Skull sceptre (i)",
   "Slayer's staff",
   "Slayer's staff (e)",
   "Smoke ancient sceptre",
   "Smoke battlestaff",
   "Snowball",
   "Spork",
   "Staff",
   "Staff of air",
   "Staff of balance",
   "Staff of bob the cat",
   "Staff of earth",
   "Staff of fire",
   "Staff of light",
   "Staff of the dead",
   "Staff of water",
   "Stale baguette",
   "Statius's warhammer (bh)",
   "Steam battlestaff",
   "Steam battlestaff (or)",
   "Steel axe",
   "Steel battleaxe",
   "Steel crossbow",
   "Steel dagger",
   "Steel dart",
   "Steel hasta",
   "Steel knife",
   "Steel longsword",
   "Steel mace",
   "Steel pickaxe",
   "Steel scimitar",
   "Steel sword",
   "Steel thrownaxe",
   "Steel warhammer",
   "Swift blade",
   "Teacher wand",
   "Thammaron's sceptre (a)",
   "Thammaron's sceptre",
   "Toktz-xil-ak",
   "Toktz-xil-ek",
   "Toktz-xil-ul",
   "Toxic staff of the dead",
   "Trailblazer axe",
   "Trailblazer cane",
   "Trailblazer harpoon",
   "Trailblazer pickaxe",
   "Trailblazer reloaded torch",
   "Training sword",
   "Treasure flag",
   "Trident of the seas",
   "Trident of the swamp",
   "Trollweiss",
   "Tzhaar-ket-em",
   "Ursine chainmace",
   "Vesta's blighted longsword",
   "Vesta's longsword (bh)",
   "Viggora's chainmace",
   "Void knight mace",
   "Voidwaker",
   "Volatile nightmare staff",
   "Volcanic abyssal whip",
   "Warped sceptre",
   "Water battlestaff",
   "White battleaxe",
   "White dagger",
   "White flowers",
   "White longsword",
   "White mace",
   "White magic staff",
   "White scimitar",
   "White sword",
   "White warhammer",
   "Wilderness sword 1",
   "Wilderness sword 2",
   "Wilderness sword 3",
   "Wilderness sword 4",
   "Willow blackjack",
   "Willow blackjack(d)",
   "Willow blackjack(o)",
   "Wolfbane",
   "Wooden spoon",
   "Wooden sword",
   "Yellow flowers",
   "Zamorak crozier",
   "Zamorak staff",
   "Zamorakian hasta",
   "Zaryte crossbow",
   "Zombie head (Treasure Trails)",
   "Zuriel's staff (bh)"
];